### ISSUE TITLE
Houskeeping packets

### ISSUE THREAD

**Issue by ChristiaanDev** [openPanfu/GameServer#12]
I think it would be great to have some kind of API Key generated for each gameserver.
This key would be used for the housekeeping packets.
It would be great to at least have a packet that will force the GS to check for changes.
We could implement this into the CMS, so we could just edit gameservers on the fly without having to manually restart the whole program.
Obviously we could add some more packets that could for example list the amount of players in the server.

**Comment by altro50** [comment]
You can use packet 900 (CMD_INFOMESSAGE) since [1901dc6](https://github.com/openPanfu/GameServer/commit/1901dc6fb9a6a6c6c74212b6dea8501b72842575)

You can simply extend it with new commands.
