### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by altro50** [openPanfu/GameServer#2]
(Aug 10th)
Started working on this locally

- [x] Plugin API
- [x] Allow for adding new packets (Handler supports this, but it could be a bit more developer friendly)
- [x] Improve security
- [x] Command API
- [x] Good example plugins

**Comment by Zaseth** [comment]
Hello. I don't know a lot about Panfu, but I've heard that it can pretty much run on a CPPS source called Kitsune. I'm very known with CPPSes and I believe that you can create a well-made plugin system based on Kitsune's plugin system. You can find Kitsune here: https://github.com/widd/kitsune

**Comment by altro50** [comment]
@Zaseth Unfortunately, the gameserver has not been written in PHP, but in Java.
Though, it could be a good source for ideas.

I'm aware that many Panfu servers make use of kitsune, but due to personal preference I decided to go for Java using the Netty framework (https://netty.io/), my old private server (Pandaland) was also written in Java using the Netty framework and has worked very well for me (running with minimal latency with 200 bots online at once).

**Comment by Zaseth** [comment]
Yeah, Java is very well for handling socket servers. I myself have some experience with AMF as I've written AMF0 and AMF3 in JS for my ByteArray. Not going too off-topic, here's some references that you might find interesting (at least, I do)

https://github.com/FreeOffset/BallistickEMU
https://github.com/FreeOffset/StickEMU
https://github.com/FilUnderscore/Club-Penguin-Server

**Comment by altro50** [comment]
@Zaseth Funny you mention a AMF implementation in JS, because I've attempted the same initially for the InformationServer, but I ran into issues returning data to the client (The HTTP implementation changed 0xFF to 0x00, which destroys the packet.)

**Comment by Zaseth** [comment]
AMF just seems pretty useless nowadays. With websockets and HTML5 rising and Flash dying, it doesn't seem logical to implement AMF. Anyway, good luck on your project. I'll be looking forward to it as there's no open-source Panfu servers.

**Comment by altro50** [comment]
I've got time to waste, let's do this.

**Comment by altro50** [comment]
Plugin system is already very useful, the next release will include it.

**Comment by altro50** [comment]
I'm sure this is finished.
